Adapt for armhf/arm64
Signed-off-by: Christoph Willing <chris.willing@linux.com>

diff --git a/build/raspi/make-raspi b/build/raspi/make-raspi
--- a/build/raspi/make-raspi
+++ b/build/raspi/make-raspi
@@ -1,21 +1,62 @@
 #!/bin/bash
 
 
-# Create a .deb package of xkeys-server for RASPI
+# Create a .deb package of xkeys-server for RASPI using an AppImage.
 
 VERSION=$(python3 -c 'import json,sys; f=open("../../package.json"); obj=json.load(f);print(obj["version"])')
-PKG_ARCH=arm64
+ARCH=${ARCH:-$(uname -m)}
+if [ "$ARCH" = "aarch64" ]; then
+  BUILD_ARCH="arm64"
+  PKG_ARCH="arm64"
+elif [ "$ARCH" = "armv*" ]; then
+  BUILD_ARCH="armhf"
+  PKG_ARCH="armhf"
+else
+  echo "ARCH: $ARCH is not supported for RASPI"
+  exit 1
+fi
+echo "PACKAGE ARCH = $PKG_ARCH"
+#ARCH=armhf
+#PKG_ARCH=armhf
 
 # Work in the correct directory
 cd $(dirname $0)
 CWD=$(pwd)
 
-# Use pkg to generate single executable into the "application" directory
+#	Step 1 - create an executable in the "application" directory
 #
-npx pkg -t node12-linux-$PKG_ARCH --out-path application ../..
-echo "Added: $(file application/*)"
+if [ "$PKG_ARCH" = "armhf" ]; then
+	#	Creating the executable for armhf RASPI is different to
+	#	other platforms because the current vercel/pkg does not
+	#	support armv7l (the most used in recent Raspberry Pis).
+	#
+	#	For very old Pis with armv6, it is possible to build
+	#	an executable with vercel/pkg but requires using a previous
+	#	version (4.5.0) and is left as an exercise for the reader.
+	#
+	# Create the AppImage
+	./${BUILD_ARCH}.AppImage
 
-# Create the package shell
+	# Do we have the AppImage (should be in this directory).
+	[ -x xkeys-server-${BUILD_ARCH}.AppImage ] || {
+		echo "Can't find xkeys-server-${BUILD_ARCH}.AppImage to package"
+		echo " - perhaps it's just not executable?"
+		echo "Exiting now ..."
+		exit 2
+	}
+	mkdir application
+	cp -p xkeys-server-${BUILD_ARCH}.AppImage application/xkeys-server
+
+else
+	# Use pkg to generate the executable
+	#
+	npx pkg -t node12-linux-$PKG_ARCH --out-path application ../..
+	echo "Added: $(file application/*)"
+
+fi
+
+#	Step 2 - package the executable into an installer
+#
 rm -rf xkeys-server-${VERSION}_${PKG_ARCH}
 mkdir -p xkeys-server-${VERSION}_${PKG_ARCH}/lib/systemd/system
 mkdir -p xkeys-server-${VERSION}_${PKG_ARCH}/lib/udev/rules.d
